qodana:
  only:
    - master
    - merge_requests
  image:
    name: jetbrains/qodana-python
    entrypoint: [""]
  variables:
    QODANA_TOKEN: $qodana_token
  script:
    - qodana --save-report --baseline=qodana.sarif.json --results-dir=$CI_PROJECT_DIR/.qodana