@echo off
echo Running directory diagnosis...
powershell -ExecutionPolicy Bypass -File "%~dp0diagnose.ps1"
echo Starting Mashaaer Enhanced Project...
powershell -ExecutionPolicy Bypass -File "%~dp0start-mashaaer.ps1"
